server:
   port: 50001
              
---

spring:
   profiles:
      active: dev
                       
---

spring:
   profiles: uat
             
---

spring:
   profiles: sit

---

spring:
   profiles: prod