server:
   port: 50001
spring:
   application:
      name: service-gateway
   cloud:
      gateway:
         routes:
            - id: simpleservice
              uri: lb://SIMPLE-SERVICE
              predicates:
              - Path=/api/simple-service/**
              filters:
              - RewritePath=/api/simple-service(?<segment>.*), /simple-service/$\{segment}
eureka:
   instance:
      preferIpAddress: true   
                
---

spring:
   profiles:
      active: dev
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:50000/eureka                           
---

spring:
   profiles: uat
eureka:
   client:
      serviceUrl:
         defaultZone: http://ip-address1:50000/eureka/,http://ip-address2:50000/eureka/              
---

spring:
   profiles: sit

---

spring:
   profiles: prod